"""
surface.py

pytracer.integrator.surface package

Model surface integrators.

Created by Jiayao on Aug 9, 2017
Modified on Aug 13, 2017
"""
from __future__ import absolute_import
from abc import (ABCMeta, abstractmethod)
from pytracer import *
import pytracer.geometry as geo
import pytracer.aggregate as agg
import pytracer.sampler as spler
import pytracer.scene as scn
import pytracer.renderer as ren
from pytracer.integrator import Integrator

__all__ = ['SurfaceIntegrator']


class SurfaceIntegrator(Integrator):
	"""
	SurfaceIntegrator Class

	Interface for surface integrators
	"""

	@abstractmethod
	def li(self, scene: 'scn.Scene', renderer: 'ren.Renderer', ray: 'geo.RayDifferential',
			isect: 'agg.Intersection', sample: 'spler.Sample', rng=np.random.rand) -> 'Spectrum':
		"""
		li()

		Returns the outgoing radiance at the intersection
		point of a given ray with scene.
		- scene
			`scn.Scene` to be rendered
		- renderer
			`ren.Renderer` used for rendering, `li()` or `transmittance()` might
			be called
		- ray
			`geo.Ray` to evaluate incident radiance
		- isect
			First `agg.Intersection` of the ray in the `scn.Scene`
		- sample
			A `spler.Sample` generated by a `spler.Sample` for this ray.
			Might be used for MC methods.
		- rng
			Random number generator, by default `numpy.random.rand`
		"""
		raise NotImplementedError('src.core.integrator.{}.li(): abstract method '
						'called'.format(self.__class__))

